services:
  malcom:
    container_name: malcom
    build: .
    networks:
      - default
    volumes:
      - ./Malcom:/Malcom
    privileged: true

  server:
    image: nginx
    container_name: server
    # build: .
    privileged: true
    networks:
      - default
    volumes:
      - ./website:/usr/share/nginx/html

  client:
    container_name: client
    build: .
    privileged: true
    networks:
      - default
